### ISSUE TITLE
[FEAT] ... Fsv2 and  DC cpu family support on azurerm_mssql_elasticpool.elastic_pool

### ISSUE THREAD

**Issue by kaganmersin** [claranet/terraform-azurerm-db-sql#4]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since local.elastic_pool_vcore_family =  "Gen5" it's impossible to have Fsv2 or DC families in azurerm_mssql_elasticpool.elastic_pool. You can check possible values from : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_elasticpool#family

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_elasticpool.elastic_pool

**Comment by Shr3ps** [comment]
Hello,

Thanks for the issue, and sorry for this late reply.
We will add this to our backlog.

**Comment by rossifumax** [comment]
Hello @kaganmersin !

Thanks for the issue, we fixed it in [v7.7.0](https://github.com/claranet/terraform-azurerm-db-sql/tree/v7.7.0).

Keep us informed and don't hesitate to open a new PR if you've got any issues.
