### ISSUE TITLE
[BUG] Error: Output refers to sensitive values

### ISSUE THREAD

**Issue by smiguez85** [claranet/terraform-azurerm-db-sql#5]
### Community Note

Terraform enforces that the Output "sql_server" should be annotate as sensitive. In the current version of the module, it gives me the following error:
![image](https://github.com/user-attachments/assets/8acfea2a-f934-4b99-91a8-8334f13d12f8)

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.9.6 on darwin_arm64

### AzureRM Provider Version

v3.116.0

### Affected Resource(s)/Data Source(s)

output "sql_server" 

### Terraform Configuration Files

```hcl
-
```

### Debug Output/Panic Output

```shell
-
```

**Comment by Shr3ps** [comment]
Hello,

can you please provide your Terraform configuration/HCL code?
It seems you're not using this module as real module like we do in the example folder.

**Comment by smiguez85** [comment]
Hi,
I'm using this module with my Terragrunt code, with TERRAGRUNT_TFPATH=terraform.
Terragrunt module definition:
![image](https://github.com/user-attachments/assets/3f83b330-4a48-4b6a-a552-8be299959608)

Terragrunt sql code:
![image](https://github.com/user-attachments/assets/eced8860-bce9-412c-b454-56d63603e620)

**Comment by Shr3ps** [comment]
Thanks for the code @smiguez85 . So I can confirm that the main issue is from Terragrunt and the way you're using our module in "base_source_url".

You should instead create your own local module, with an HCL code similar to this: https://github.com/claranet/terraform-azurerm-db-sql/blob/master/examples/main/modules.tf
and then reference your own module in "base_source_url".
